# Generated by Django 2.0.3 on 2019-05-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='create_time',
            field=models.DateField(auto_now=True),
        ),
    ]
